config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :hotels do
    get 'rooms', on: :member
    get 'rooms/:room_number', to: 'bookings#new', as: "booking_room", on: :member
    get '/bookings', to: 'bookings#index', as: "bookings", on: :member
    post 'rooms/:room_number', to: 'bookings#create', on: :member
    get 'rooms/:room_number/bookings/:id', to: 'bookings#show', as: "show_booking_room", on: :member
    get 'rooms/:room_number/bookings/:id/edit', to: 'bookings#edit', as: "edit_booking_room", on: :member
    patch 'rooms/:room_number/bookings/:id', to: 'bookings#update', as: "update_booking_room", on: :member
    delete 'rooms/:room_number/bookings/:id', to: 'bookings#destroy', as: "destroy_booking_room", on: :member
  end

  root "hotels#home", as:"home"
  resources :users , only:[:new, :create, :edit, :update]
  get "/users/:id/bookings", to: 'bookings#index', as: "bookings"

  get "/signin", to: "sessions#new", as: "signin"
  post "/signin", to: "sessions#create"
  delete "/signout", to: "sessions#destroy", as: "signout"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :check_in_date, presence: true
  validates :check_out_date, presence: true
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :rooms
  has_many :images
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :hotel
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel
  has_many :bookings
  has_many :users, through: :bookings
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :rooms, through: :bookings
  has_secure_password
  # validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized
  helper_method :current_user

  def current_user
    User.find_by({ id:session[:user_id] })
  end

  def signed_in?
    !!current_user
  end

  def authorized
    redirect_to signin_path unless signed_in?
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
 skip_before_action :authorized, only:[:create, :update]
 before_action :find_booking, only:[:show, :edit, :update, :destroy]
  def index
    @user = User.find(session[:user_id])
    @bookings = @user.bookings
  end

  def new
    @booking = Booking.new
  end

  def show

    @room = @booking.room
    @user = User.find(session[:user_id])
  end

  def create
    @room_number = params[:room_number]
    @user_id = session[:user_id]
    @booking = Booking.create(booking_params)
    if @booking.valid?
     redirect_to show_booking_room_hotel_path(@booking)
   else
     flash[:errors] = @booking.errors.full_messages
     redirect_to booking_room_hotel_path(@booking)
   end
  end

  def edit
  end

  def update
    @room_number = params[:room_number]
    @user_id = session[:user_id]
    @booking.update(booking_params)
    if @booking.valid?
     redirect_to show_booking_room_hotel_path(@booking)
   else
     flash[:errors] = @booking.errors.full_messages
     redirect_to edit_booking_room_hotel_path(@booking)
   end
  end

  def destroy
    @booking.destroy
    flash[:notice] = "My booking was deleted!"
    redirect_to bookings_hotel_path
  end

  private

 def find_booking
    @booking = Booking.find(params[:id])
 end

  def booking_params
    params.require(:booking).permit(:check_in_date, :check_out_date, :num_rooms, :num_ppl, :room_id).merge( user_id: @user_id, room_id: @room_number)
  end

end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController

  def home
    @user = User.find(session[:user_id])

    @hotels = Hotel.all
  end

  def show
    @hotel = Hotel.find(params[:id])
    @rooms = @hotel.rooms
    @images = @hotel.images
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only:[:new, :create]
  def new
   render :new
  end

  def create
   @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to home_path
    else
      flash[:notice] = "The email and password combination you entered doesn't match."
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You signed out"
    redirect_to home_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only:[:new, :create]
  before_action :find_user, only: [:show, :edit, :update]
  def new
   @user = User.new
  end

  def show
  end

  def create
    @user = User.create(user_params)
    # sign up and create a user,get his id,save it to session
    session[:user_id] = @user.id
    # keeps the user logging in
    redirect_to home_path
  end

  def edit
    @user = User.create(user_params)
    redirect_to home_path
  end

  def update
  end

  private
  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    # change :password_digest to :password, cuz in User model we set has_secure_password
    # that will convert password to password_digest automatically for us
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/edit.html.erb
<div class="all">
<h1>Edit My Booking</h1>
<% if flash[:errors] %>
<% flash[:errors].each do|error| %>
<p><%=  error %></p>
<% end %>
<% end %>
<%= form_for @booking,  url: update_booking_room_hotel_path do |f| %>
  <%= f.label "Check-in:" %><br>
  <%= f.text_field :check_in_date, placeholder:"YYYY/MM/DD"%><br><br>
  <%= f.label "Check-out:" %><br>
  <%= f.text_field :check_out_date, placeholder:"YYYY/MM/DD" %><br><br>
  <%= f.label "Guests:" %>
  <%= f.select :num_ppl, (1..4) %><br><br>
  <%= f.label "Rooms:" %>
  <%= f.select :num_rooms, (1..10) %><br><br>
  <%= f.submit "Edit" %>
<% end %>
</div>

app/views/bookings/index.html.erb
<div class="all">
<h1>My Bookings</h1>
<ul>
  <% @bookings.each do|booking|%>
  <li><%= booking.room.hotel.name %>, <%= booking.room.room_type%> </li>
  <% end %>
</ul>
<%= button_to "Check More Hotels", home_path, method: :get, class:"btn btn-success btn-sm" %>
</div>

app/views/bookings/new.html.erb
<div class="all">
  <h1>My New Booking</h1>
</div>

<% if flash[:errors] %>
<% flash[:errors].each do|error| %>
<p><%=  error %></p>
<% end %>
<% end %>
<div class="info-container">
  <div class="room-type-info">
<%= form_for @booking,  url: booking_room_hotel_path do |f| %>
  <%= f.label "Check-in:" %><br>
  <%= f.text_field :check_in_date, placeholder:"YYYY/MM/DD"%><br><br>
  <%= f.label "Check-out:" %><br>
  <%= f.text_field :check_out_date, placeholder:"YYYY/MM/DD" %><br><br>
  <%= f.label "Guests:" %>
  <%= f.select :num_ppl, (1..4) %><br><br>
  <%= f.label "Rooms:" %>
  <%= f.select :num_rooms, (1..10) %><br><br>
  <%= f.submit "Confirm" %>
<% end %>
</div>
</div>

app/views/bookings/show.html.erb
<div class="all">
<h1>My Booking Details</h1>
<h3>Customer Info</h3>
<p>First Name: <%= @user.first_name %></p>
<p>Last Name: <%= @user.last_name %></p>

<h3>Check in & Check out</h3>
  <p>Check in date:  <%=  DateTime.parse(@booking.check_in_date).strftime("%B %d, %Y, %A")%></p>
  <p>Check out date:  <%= DateTime.parse(@booking.check_out_date).strftime("%B %d, %Y, %A") %></p>
  <% if @booking.num_ppl == 1%>
   <p><%= @booking.num_ppl %> Adult</p>
   <% else %>
  <p><%= @booking.num_ppl %> Adults</p>
  <% end %>

<h3>Room Details</h3>
  <p><%= @room.room_type %></p>

<h3>Price Summary</h3>
<p>
  <% total_nt = (Date.parse(@booking.check_out_date) - Date.parse(@booking.check_in_date)).to_i %>
  <% if total_nt == 1 && @booking.num_rooms == 1 %>
  <%= total_nt %> Night, <%= @booking.num_rooms %> Room
  <% elsif total_nt > 1 && @booking.num_rooms == 1 %>
  <%= total_nt %> Nights, <%= @booking.num_rooms %> Room
  <% elsif total_nt == 1 && @booking.num_rooms > 1 %>
  <%= total_nt %> Night, <%= @booking.num_rooms %> Rooms
  <% else %>
  <%= total_nt %> Nights, <%= @booking.num_rooms %> Rooms
  <% end %>
</p>
  <p>Room Price: $ <%= total = @room.rate * @booking.num_rooms * total_nt%></p>
  <p>Taxes: $ <%= tax = (total * 0.1475).to_f.round(2) %></p>
  <p>Room Total: $ <%= total + tax %></p>
<div class="button-to">
  <%= button_to "Edit My Booking", edit_booking_room_hotel_path(@booking), method: :get %><br>
  <%= button_to "Delete My Booking", destroy_booking_room_hotel_path(@booking), method: :delete, data: { confirm:"Are you sure?" } %><br>
  <%= button_to "View My Bookings", bookings_hotel_path, method: :get %><br>
  </div>
</div>

app/views/hotels/home.html.erb
<hearder>
<h1>hotelfinder<%= image_tag("jing.jpg", size:"28x28") %></h1>
<% if @user.valid? %>
<p>Welcome, <%= @user.first_name %>!</p>
<div class="sign">
<%= button_to "Sign out", signout_path, method: :delete %>
<% else %>
<%= button_to "Sign In", signin_path, method: :get %>
<%= button_to "Sign Up", new_user_path, method: :get %>
<% end %>
</div>
<ul>
<br>
<main>
<div class="hotel-container">
 <% @hotels.each do|hotel| %>
  <div class="hotel-card">
    <div class="hotel-image-container"><%= image_tag(hotel.img_url, size:"330x280") %></div><br>
    <%= link_to hotel.name, hotel %>
      <blink><strong><%= "GO!" %></strong></blink>
      <p><%= hotel.location %></p>
      <p><%= hotel.amenities %></p>
  </div>
  <% end %>
</ul>
</div>

app/views/hotels/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="http://localhost:3000">hotelfinder<%= image_tag("jing.jpg", size:"28x28") %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="http://localhost:3000">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="#room-info">Room Information</a>
      <a class="nav-item nav-link" href="#room-info">Check Price</a>
      <a class="nav-item nav-link" href="http://localhost:3000/users/:id/bookings">View My Bookings</a>
    </div>
  </div>
</nav>
<div class="all">
<h1><%= @hotel.name %></h1>
<p><%= @hotel.location %></p>

<div class="hr-image-container">
  <% @images.each do|image| %>
  <div class="image-card"><%= image_tag(image.name, size:"350x280") %></div>
  <% end %>
</div>
</div>
<!-- class="image-container" -->
<div id="room-info">
<div class="info-container">
  <div class="room-type-info">
    <h3>Room Type</h3>
    <table>
      <tr>
        <th>Room Type</th>
        <th>Room Rate</th>
      </tr>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.room_type %></td>
        <td>$<%= room.rate %><%= button_to "BOOK NOW", booking_room_hotel_path(@hotel, room), method: :get, class:"btn btn-warning btn-sm" %></td>
      </tr>
    <% end %>
    </table>
  </div>
  <div class="amendities-info">
    <h3>Amenities</h3>
    <p><%= @hotel.amenities %></p>
    <%= button_to "Check More Hotels", home_path, method: :get, class:"btn btn-success btn-sm" %>
  </div>
</div>
</div>
<br>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelFinder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
<footer>
<div class="bg-copyright">
   Copyright(C) 2012-2019 HotelFinder Co., Ltd. All Rights Reserved.
</div>
</html>

app/views/users/edit.html.erb
<h1>Edit My Account</h1>
<%= form_for @user do |f| %>
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %><br><br>
  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %><br><br>
  <%= f.label :password %><br>
  <%= f.password_field :password %><br><br>
  <%= f.submit "Edit Account"%><br>
<% end %>

app/views/users/new.html.erb
<div class="all">
<h1>Create My Account</h1>
<%= form_for @user do |f| %>
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %><br><br>
  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %><br><br>
  <%= f.label :email %><br>
  <%= f.email_field :email %><br><br>
  <%= f.label :password %><br>
  <%= f.password_field :password %><br><br>
  <%= f.submit "Create Account"%><br>
<% end %>
</div>